"use client";

import { Heart, MessageCircle, Trophy, UserRound } from "lucide-react";
import { BlurText } from "@/components/motion/blur-text";
import { Counter } from "@/components/motion/counter";
import { Reveal } from "@/components/motion/reveal";
import { useAppMode } from "@/features/app-mode/app-mode-context";
import { demoDisplayReports } from "@/features/app-mode/mode-data";
import { useIncidentsQuery } from "@/features/incidents/queries";

export default function CommunityPage() {
  const { mode } = useAppMode();
  const liveIncidents = useIncidentsQuery(mode === "live" ? "?limit=100&sort=desc" : "");
  const demoPosts = demoDisplayReports.map((report) => ({ id: report.id, person: report.reporter, text: report.description, time: new Date(report.createdAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }), trust: report.trustScore }));
  const livePosts = liveIncidents.data?.items.map((incident) => ({ id: incident.id, person: "Live map incident", text: `${incident.category.replaceAll("_", " ")} reported at ${incident.latitude.toFixed(4)}, ${incident.longitude.toFixed(4)}.`, time: new Date(incident.lastReportedAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }), trust: incident.confidenceScore === null ? null : Math.round(incident.confidenceScore) })) ?? [];
  const posts = mode === "demo" ? demoPosts : livePosts;
  const contributors = mode === "demo" ? [...demoPosts].sort((a, b) => (b.trust ?? 0) - (a.trust ?? 0)) : [];

  return <main className="mx-auto grid max-w-6xl gap-4 px-5 py-10 lg:grid-cols-[1fr_19rem]"><section><p className="text-xs font-semibold tracking-[.18em] text-blue-400">COMMUNITY PULSE · {mode.toUpperCase()} DATA</p><BlurText as="h1" text="Reports from people nearby" delay={140} className="mt-2 text-3xl font-semibold tracking-[-.04em]" /><p className="mt-2 text-sm text-zinc-500">{mode === "demo" ? <><Counter value={demoPosts.length} fontSize={15} /> shared demo contributors and their reports.</> : "Current live map incidents. Live contributor identities are not exposed by the service."}</p><div className="mt-7 space-y-3">{posts.map((post, index) => <Reveal key={post.id} delay={Math.min(index * 0.04, 0.24)}><article className="surface-card rounded-2xl p-5"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-blue-500/15 text-blue-300"><UserRound className="size-4" /></span><div><p className="text-sm font-semibold">{post.person}</p><p className="text-xs text-zinc-500">{mode === "demo" ? "Trust score" : "Confidence"} {post.trust === null ? "—" : <Counter value={post.trust} fontSize={12} />} · {post.time}</p></div></div><p className="mt-5 text-sm leading-6 text-zinc-300">{post.text}</p><div className="mt-5 flex gap-4 text-xs text-zinc-500"><button className="inline-flex items-center gap-1 hover:text-red-300"><Heart className="size-4" />Helpful</button><button className="inline-flex items-center gap-1 hover:text-blue-300"><MessageCircle className="size-4" />Comment</button></div></article></Reveal>)}{posts.length === 0 ? <article className="surface-card rounded-2xl p-5 text-sm text-zinc-500">{liveIncidents.isLoading ? "Loading live community data…" : "No live community data is available."}</article> : null}</div></section><Reveal><aside className="surface-card h-fit rounded-2xl p-5"><p className="flex items-center gap-2 text-sm font-semibold"><Trophy className="size-4 text-amber-300" />Top contributors</p>{mode === "demo" ? <ol className="mt-5 space-y-4">{contributors.map((contributor, index) => <li className="flex items-center gap-3" key={contributor.id}><span className="grid size-6 place-items-center rounded-full bg-white/[.06] text-xs text-zinc-400"><Counter value={index + 1} fontSize={11} /></span><span className="flex-1 text-sm">{contributor.person}</span><span className="text-xs text-emerald-400">{contributor.trust === null ? "—" : <Counter value={contributor.trust} fontSize={12} textColor="rgb(52 211 153)" />}</span></li>)}</ol> : <p className="mt-5 text-xs leading-5 text-zinc-500">Contributor standings are not part of the live data feed.</p>}</aside></Reveal></main>;
}
