"use client";

import { useState } from "react";
import { parseCoordinate, serializeCoordinate, type LocationValue } from "@/features/map/types";

export function LocationPicker({ value, onChange }: { value: LocationValue | null; onChange: (value: LocationValue) => void }) {
  const [latitude, setLatitude] = useState(value ? serializeCoordinate(value.latitude) : ""); const [longitude, setLongitude] = useState(value ? serializeCoordinate(value.longitude) : ""); const [editing, setEditing] = useState(false); const [error, setError] = useState<string | null>(null);
  function commit() { const nextLatitude = parseCoordinate(latitude, -85.051128, 85.051128); const nextLongitude = parseCoordinate(longitude, -180, 180); if (nextLatitude === null || nextLongitude === null) { setError("Enter valid coordinates."); return; } setError(null); setEditing(false); onChange({ locationSource: "MANUAL", latitude: nextLatitude, longitude: nextLongitude, gpsAccuracy: null }); }
  return <section aria-labelledby="location-heading"><h2 id="location-heading">Location</h2><p aria-live="polite">{value ? `${serializeCoordinate(value.latitude)}, ${serializeCoordinate(value.longitude)}` : "No location selected"}</p>{value && !editing ? <button type="button" onClick={() => setEditing(true)}>Edit coordinates</button> : null}<label htmlFor="latitude">Latitude</label><input id="latitude" inputMode="decimal" value={latitude} readOnly={Boolean(value && !editing)} onChange={(event) => setLatitude(event.target.value)} aria-invalid={error !== null} /><label htmlFor="longitude">Longitude</label><input id="longitude" inputMode="decimal" value={longitude} readOnly={Boolean(value && !editing)} onChange={(event) => setLongitude(event.target.value)} aria-invalid={error !== null} />{editing ? <><button type="button" onClick={commit}>Use these coordinates</button><button type="button" onClick={() => setEditing(false)}>Cancel coordinate editing</button></> : null}{error ? <p role="alert">{error}</p> : null}</section>;
}
