"use client";

import { useEffect, useRef, useState } from "react";
import type { Map as MapLibreMap, StyleSpecification } from "maplibre-gl";
import type { MapViewport } from "@/features/map/types";
import type { IncidentDto, ReportMapDto } from "@/lib/api/contracts";
import type { RoadPath } from "@/features/map/demo-preview-incidents";

export type MapLayerState = { roads: boolean; markers: boolean; heatmap: boolean; shelters: boolean; weather: boolean; traffic: boolean };
type MapPointDto = IncidentDto | ReportMapDto;
const emptyPoints: readonly MapPointDto[] = [];
const emptyRoadPaths: Readonly<Record<string, RoadPath>> = {};
const emptyRoutes: readonly { coordinates: RoadPath; color: string }[] = [];
const severityForPoint = (point: MapPointDto) => "severity" in point ? point.severity : point.severityClaim;
const statusForPoint = (point: MapPointDto) => "status" in point ? point.status : point.verificationStatus;
const colorForPoint = (point: MapPointDto): string => statusForPoint(point) === "STALE" || statusForPoint(point) === "MONITORING" || statusForPoint(point) === "RESOLVED" || severityForPoint(point) === "MODERATE" ? "#d97706" : severityForPoint(point) === "SEVERE" || severityForPoint(point) === "IMPASSABLE" ? "#dc2626" : severityForPoint(point) === "UNKNOWN" ? "#2563eb" : "#facc15";
const escapePopupText = (value: string) => value.replace(/[&<>\"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '\"': "&quot;", "'": "&#39;" })[character] ?? character);
const incidentBands = (incidents: readonly MapPointDto[], roadPaths: Readonly<Record<string, RoadPath>>) => ({ type: "FeatureCollection" as const, features: incidents.flatMap((incident) => { const roadPath = roadPaths[incident.id]; return roadPath === undefined ? [] : [{ type: "Feature" as const, properties: { id: incident.id, color: colorForPoint(incident) }, geometry: { type: "LineString" as const, coordinates: roadPath } }]; }) });
const incidentPoints = (incidents: readonly MapPointDto[]) => ({ type: "FeatureCollection" as const, features: incidents.map((incident) => ({ type: "Feature" as const, properties: { id: incident.id, color: colorForPoint(incident), category: incident.category, severity: severityForPoint(incident) }, geometry: { type: "Point" as const, coordinates: [incident.longitude, incident.latitude] } })) });
const shelters = { type: "FeatureCollection" as const, features: [{ type: "Feature" as const, properties: { name: "Gurugram Community Hall" }, geometry: { type: "Point" as const, coordinates: [77.051, 28.334] } }, { type: "Feature" as const, properties: { name: "Sector 22 Relief Centre" }, geometry: { type: "Point" as const, coordinates: [77.067, 28.346] } }] };
const weather = { type: "FeatureCollection" as const, features: [{ type: "Feature" as const, properties: {}, geometry: { type: "Polygon" as const, coordinates: [[[77.01, 28.29], [77.11, 28.29], [77.11, 28.38], [77.01, 28.38], [77.01, 28.29]]] } }] };
const cartoDarkMatterStyle: StyleSpecification = { version: 8, sources: { carto: { type: "raster", tiles: ["https://a.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png", "https://b.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png", "https://c.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png", "https://d.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png"], tileSize: 256, attribution: "© OpenStreetMap contributors © CARTO" } }, layers: [{ id: "carto-dark", type: "raster", source: "carto", minzoom: 0, maxzoom: 20 }] };

export function MapCanvas({ viewport, attribution, styleUrl, incidents = emptyPoints, roadPaths = emptyRoadPaths, routes = emptyRoutes, layers, selectedIncidentId, onIncidentSelect, location, onMapLocationSelect }: { viewport: MapViewport; attribution: string; styleUrl: string; incidents?: readonly MapPointDto[]; roadPaths?: Readonly<Record<string, RoadPath>>; routes?: readonly { coordinates: RoadPath; color: string }[]; layers: MapLayerState; selectedIncidentId?: string | null | undefined; onIncidentSelect?: (incidentId: string) => void; location?: { latitude: number; longitude: number } | null; onMapLocationSelect?: ((location: { latitude: number; longitude: number }) => void) | undefined }) {
  const container = useRef<HTMLDivElement>(null); const mapRef = useRef<MapLibreMap | null>(null); const [loadError, setLoadError] = useState(false);
  useEffect(() => {
    let active = true; setLoadError(false); const bands = incidentBands(incidents, roadPaths); const points = incidentPoints(incidents); const routeFeatures = { type: "FeatureCollection" as const, features: routes.map((route) => ({ type: "Feature" as const, properties: { color: route.color }, geometry: { type: "LineString" as const, coordinates: route.coordinates } })) }; const selectedLocation = { type: "FeatureCollection" as const, features: location === null || location === undefined ? [] : [{ type: "Feature" as const, properties: {}, geometry: { type: "Point" as const, coordinates: [location.longitude, location.latitude] as [number, number] } }] };
    void import("maplibre-gl").then(({ Map, Popup }) => { if (!active || container.current === null) return; const mapStyle = styleUrl.includes("openfreemap.org") || styleUrl.includes("cartocdn.com") ? cartoDarkMatterStyle : styleUrl; const map = new Map({ container: container.current, style: mapStyle, center: [viewport.longitude, viewport.latitude], zoom: viewport.zoom, minZoom: 1, maxZoom: 18, attributionControl: false }); mapRef.current = map;
      let styleLoaded = false;
      map.on("error", () => { if (active && !styleLoaded) setLoadError(true); });
      map.once("load", () => { if (!active) return; styleLoaded = true;
        map.addSource("incident-bands", { type: "geojson", data: bands }); map.addSource("incident-points", { type: "geojson", data: points }); map.addSource("shelters", { type: "geojson", data: shelters }); map.addSource("weather", { type: "geojson", data: weather }); map.addSource("selected-location", { type: "geojson", data: selectedLocation }); map.addSource("routes", { type: "geojson", data: routeFeatures });
        map.addLayer({ id: "weather", type: "fill", source: "weather", paint: { "fill-color": "#2563eb", "fill-opacity": 0.12 } });
        map.addLayer({ id: "route-shadow", type: "line", source: "routes", paint: { "line-color": "#020617", "line-width": 10, "line-opacity": 0.55 } }); map.addLayer({ id: "routes", type: "line", source: "routes", paint: { "line-color": ["get", "color"], "line-width": 5, "line-opacity": 0.95 } });
        map.addLayer({ id: "incident-band-shadow", type: "line", source: "incident-bands", paint: { "line-color": "#020617", "line-opacity": 0.45, "line-width": 13, "line-blur": 2 } });
        map.addLayer({ id: "incident-bands", type: "line", source: "incident-bands", paint: { "line-color": ["get", "color"], "line-width": 6, "line-opacity": 0.94 } });
        map.addLayer({ id: "traffic", type: "line", source: "incident-bands", paint: { "line-color": "#ffffff", "line-opacity": 0.75, "line-width": 1.5, "line-dasharray": [1, 2] } });
        map.addLayer({ id: "heatmap", type: "heatmap", source: "incident-points", paint: { "heatmap-weight": 1, "heatmap-intensity": 1.2, "heatmap-radius": 38, "heatmap-opacity": 0.7, "heatmap-color": ["interpolate", ["linear"], ["heatmap-density"], 0, "rgba(59,130,246,0)", 0.35, "#2563eb", 0.7, "#facc15", 1, "#ef4444"] } });
        map.addLayer({ id: "incident-points", type: "circle", source: "incident-points", paint: { "circle-color": ["get", "color"], "circle-radius": 7, "circle-stroke-color": "#ffffff", "circle-stroke-width": 2.2 } });
        map.addLayer({ id: "selected-incident", type: "circle", source: "incident-points", filter: ["==", ["get", "id"], ""], paint: { "circle-color": "transparent", "circle-radius": 13, "circle-stroke-color": "#ffffff", "circle-stroke-width": 2.5 } });
        map.addLayer({ id: "shelters", type: "circle", source: "shelters", paint: { "circle-color": "#38bdf8", "circle-radius": 7, "circle-stroke-color": "#ffffff", "circle-stroke-width": 2 } });
        map.addLayer({ id: "selected-location-radius", type: "circle", source: "selected-location", paint: { "circle-color": "#ffffff", "circle-opacity": 0.10, "circle-radius": 42, "circle-stroke-color": "#ffffff", "circle-stroke-opacity": 0.55, "circle-stroke-width": 1 } }); map.addLayer({ id: "selected-location", type: "circle", source: "selected-location", paint: { "circle-color": "#ffffff", "circle-radius": 8, "circle-stroke-color": "#111113", "circle-stroke-width": 2 } });
        const visibility = (id: string, enabled: boolean) => map.setLayoutProperty(id, "visibility", enabled ? "visible" : "none");
        visibility("incident-band-shadow", layers.roads); visibility("incident-bands", layers.roads); visibility("traffic", layers.roads && layers.traffic); visibility("incident-points", layers.markers); visibility("selected-incident", layers.markers); visibility("heatmap", layers.heatmap); visibility("shelters", layers.shelters); visibility("weather", layers.weather);
        map.setFilter("selected-incident", ["==", ["get", "id"], selectedIncidentId ?? ""]);
        map.on("mouseenter", "incident-points", () => { map.getCanvas().style.cursor = "pointer"; }); map.on("mouseleave", "incident-points", () => { map.getCanvas().style.cursor = ""; });
        map.on("click", "incident-points", (event) => { const feature = event.features?.[0]; const id = String(feature?.properties?.id ?? ""); if (id === "") return; onIncidentSelect?.(id); const category = String(feature?.properties?.category ?? "Incident").replaceAll("_", " "); const severity = String(feature?.properties?.severity ?? ""); new Popup({ closeButton: false, offset: 12 }).setLngLat(event.lngLat).setHTML(`<div style="min-width:150px;color:#182238 !important"><strong style="display:block;color:#182238 !important;text-transform:uppercase;letter-spacing:.04em">${escapePopupText(category)}</strong><span style="display:block;margin-top:4px;color:#182238 !important">${escapePopupText(severity)}</span></div>`).addTo(map); });
        if (onMapLocationSelect !== undefined) map.on("click", (event) => onMapLocationSelect({ latitude: event.lngLat.lat, longitude: event.lngLat.lng }));
      });
    }).catch(() => { if (active) setLoadError(true); });
    return () => { active = false; mapRef.current?.remove(); mapRef.current = null; };
  }, [incidents, roadPaths, routes, styleUrl, viewport.latitude, viewport.longitude, viewport.zoom, onIncidentSelect, location, onMapLocationSelect]);
  useEffect(() => { const map = mapRef.current; if (map === null || !map.isStyleLoaded()) return; const visibility = (id: string, enabled: boolean) => map.setLayoutProperty(id, "visibility", enabled ? "visible" : "none"); visibility("incident-band-shadow", layers.roads); visibility("incident-bands", layers.roads); visibility("traffic", layers.roads && layers.traffic); visibility("incident-points", layers.markers); visibility("selected-incident", layers.markers); visibility("heatmap", layers.heatmap); visibility("shelters", layers.shelters); visibility("weather", layers.weather); }, [layers]);
  useEffect(() => { const map = mapRef.current; if (map === null || !map.isStyleLoaded()) return; map.setFilter("selected-incident", ["==", ["get", "id"], selectedIncidentId ?? ""]); }, [selectedIncidentId]);
  useEffect(() => { const incident = incidents.find((item) => item.id === selectedIncidentId); const map = mapRef.current; if (incident !== undefined && map !== null) map.flyTo({ center: [incident.longitude, incident.latitude], zoom: Math.max(map.getZoom(), 14), essential: true }); }, [incidents, selectedIncidentId]);
  return <section aria-label="FloodReady map" className="h-full overflow-hidden bg-[#0d1015]"><div ref={container} className="h-full w-full bg-[#0d1015]" />{loadError ? <p role="status" className="absolute bottom-5 left-1/2 -translate-x-1/2 rounded-xl border border-amber-400/25 bg-[#17171a] px-4 py-3 text-sm text-amber-200 shadow-xl">The basemap could not load. Map overlays are still available.</p> : null}<span className="absolute bottom-2 right-3 text-[10px] text-zinc-600">{attribution}</span></section>;
}
